### ISSUE TITLE
DiscordEmoji.com API integration

### ISSUE THREAD

**Issue by dtmcode** [ohlookitsderpy/discord-emoji#4]
I made recently made this site, maybe you could support adding emoji using the API 

https://discordemoji.com/api

Image path is as follows: `http://discordemoji.com/assets/emoji/<slug>.png`

Categories:

1 = Original Style
2 = TV / Movie
3 = Meme
4 = Anime
5 = Celebrity
6 = Blob
7 = Thinking

**Comment by ohlookitsderpy** [comment]
Thanks for the suggestion! 

By "adding emoji", do you mean adding emoji to the site or grabbing download URLs for them?

**Comment by dtmcode** [comment]
Adding emoji to a discord server, or using it to "search" for emoji and return a link

**Comment by ohlookitsderpy** [comment]
Does your site have a Discord server and a way to add emoji to the website?

**Comment by ohlookitsderpy** [comment]
Would it be possible to search and return info about an emoji via the API as well?

**Comment by dtmcode** [comment]
Sure, will add that to the API today

**Comment by ohlookitsderpy** [comment]
™️

**Comment by ohlookitsAugust** [comment]
same lol

**Comment by dtmcode** [comment]
My b

https://discordemoji.com/api?request=search&q=merry

**Comment by ohlookitsAugust** [comment]
This is easy, maybe I can add it.

**Comment by ohlookitsAugust** [comment]
This has been added to `commands/emote.js`. Cased closed.
